sudo apt-get install php8.1-tidy
sudo apt-get install php8.1-gd
sudo apt-get install php8.1-common
sudo apt-get install php8.1-mcrypt
sudo apt-get install php8.1-mbstring
sudo apt-get install php8.1-mysql
#sudo apt-get install php8.1-session
sudo apt-get install php8.1-xml
sudo apt install libapache2-mod-php8.1
sudo apt install php8.1-curl
sudo apt install php8.1-xmlrpc
sudo apt install php8.1-intl